# This file was generated by GoReleaser. DO NOT EDIT.
cask "portpeek" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "ee98436be6e30527b5098c4b812e8b9f37e1461fdfb9c71bde29a2357b636e7b"
      url "https://github.com/KaanEmec/portpeek/releases/download/v#{version}/portpeek_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8e1ec4a7da5171b42681f1336474f3bf30671d35ea5f4094b2e7d8474ac5d4f6"
      url "https://github.com/KaanEmec/portpeek/releases/download/v#{version}/portpeek_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2c1755757e8aec2f9a7e15b87a7d388dd5136106f7b0f25c607088b06d65d709"
      url "https://github.com/KaanEmec/portpeek/releases/download/v#{version}/portpeek_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6383b51e36d926590aa1ffd4359b1afdcb2c7352e381d5e747a1d798b0e0aaf8"
      url "https://github.com/KaanEmec/portpeek/releases/download/v#{version}/portpeek_#{version}_linux_amd64.tar.gz"
    end
  end

  name "portpeek"
  desc "What is using this port? Process, PID, command and exposure, plus a live TUI"
  homepage "https://github.com/kaanemec/portpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portpeek"]
    end
  end

  # No zap stanza required
end
