# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewboard < Formula
  desc "Keyboard-first terminal interface for routine Homebrew maintenance"
  homepage "https://github.com/KaanEmec/brew-board"
  version "1.0.0-rc.5"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/KaanEmec/brew-board/releases/download/v1.0.0-rc.5/brewboard_1.0.0-rc.5_darwin_amd64.tar.gz"
    sha256 "4806d5ccf5bb3b2b416ecc10742af8a3063d00bcc4cfd1979ce44f7a21045af5"

    define_method(:install) do
      bin.install "brewboard"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/KaanEmec/brew-board/releases/download/v1.0.0-rc.5/brewboard_1.0.0-rc.5_darwin_arm64.tar.gz"
    sha256 "5ac62bac8aee0fd631c67826f446291a13f094ed4e56369cfd63ff211b054a66"

    define_method(:install) do
      bin.install "brewboard"
    end
  end

  test do
    system "#{bin}/brewboard", "--version"
  end
end
